services:
  - type: web
    name: cinescore-app
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /tmp
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.19.2
